### ISSUE TITLE
Windows 10 FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by leondavi** [DAI-Lab/TGAN#2]
Running TGAN on windows 10 and getting the following error: 

`Traceback (most recent call last):
  File "src/launcher.py", line 134, in <module>
    run_experiment(task)
  File "src/launcher.py", line 108, in run_experiment
    evaluate_res = pool.map(evaluate_worker, commands)
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 670, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'expdir\\census\\synthetic0_-1.npz'`

I can't find the reason why the syntetic.npz file wasn't created since the training phase
had finished. 
This is the error I get right after the training finished: 
`2019-01-15 13:52:40.119025: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "src/TGAN_synthesizer.py", line 314, in <module>
    sample(args.sample, Model(), args.load, output_filename=args.output)
  File "src/TGAN_synthesizer.py", line 235, in sample
    session_init=get_model_loader(model_path),
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\sessinit.py", line 262, in get_model_loader
    return SaverRestore(filename)
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\sessinit.py", line 107, in __init__
    model_path = get_checkpoint_path(model_path)
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\varmanip.py", line 182, in get_checkpoint_path
    assert tf.gfile.Exists(model_path) or tf.gfile.Exists(model_path + '.index'), model_path
AssertionError: train_log/TGAN_synthesizer:census-4/model--1000
Traceback (most recent call last):
  File "src/TGAN_synthesizer.py", line 314, in <module>
    sample(args.sample, Model(), args.load, output_filename=args.output)
  File "src/TGAN_synthesizer.py", line 235, in sample
    session_init=get_model_loader(model_path),
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\sessinit.py", line 262, in get_model_loader
    return SaverRestore(filename)
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\sessinit.py", line 107, in __init__
    model_path = get_checkpoint_path(model_path)
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\varmanip.py", line 182, in get_checkpoint_path
    assert tf.gfile.Exists(model_path) or tf.gfile.Exists(model_path + '.index'), model_path
AssertionError: train_log/TGAN_synthesizer:census-4/model-0
Traceback (most recent call last):
  File "src/TGAN_synthesizer.py", line 314, in <module>
    sample(args.sample, Model(), args.load, output_filename=args.output)
  File "src/TGAN_synthesizer.py", line 235, in sample
    session_init=get_model_loader(model_path),
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\sessinit.py", line 262, in get_model_loader
    return SaverRestore(filename)
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\sessinit.py", line 107, in __init__
    model_path = get_checkpoint_path(model_path)
  File "C:\Users\David Leon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorpack\tfutils\varmanip.py", line 182, in get_checkpoint_path
    assert tf.gfile.Exists(model_path) or tf.gfile.Exists(model_path + '.index'), model_path
AssertionError: train_log/TGAN_synthesizer:census-4/model-1000`

Thanks in advance for your time and your help.

**Comment by lapidshay** [comment]
same problem here.
thanks in advance

**Comment by SwearyStats** [comment]
I also have the exact same problem and cannot get this to work on Windows 10 but appears to run with minimal alteration fine on Linux. 


thanks in advance

**Comment by leix28** [comment]
This issue is caused by the multi-processing mechanism on windows. I uploaded `launcher_simple.py` which removes the process pools. It should work on Windows now.
