### ISSUE TITLE
Version of tensorpack?

### ISSUE THREAD

**Issue by Zhiyu-Chen** [DAI-Lab/TGAN#5]
Got the following error:
```
    from tensorpack.utils.globvars import globalns as opt
ModuleNotFoundError: No module named 'tensorpack.utils.globvars'
```

It seems the newest version of tensorpack is not compatible with the version used in the implementation.

**Comment by leix28** [comment]
Please try tensorpack 0.8.9. Sorry for the inconvenience.

**Comment by mrdixitjain** [comment]
with tensorpack 0.8.9, i'm having another issue with tensorflow
it says AttributeError: module 'tensorflow' has no attribute 'VERSION'

and i'm getting same error with tensorpack 0.10.1

Traceback (most recent call last):
  File "TGAN_synthesizer.py", line 14, in <module>
    from tensorpack import *
  File "venv/lib/python3.8/site-packages/tensorpack/__init__.py", line 17, in <module>
    from tensorpack.models import *
  File "venv/lib/python3.8/site-packages/tensorpack/models/__init__.py", line 49, in <module>
    _global_import(module_name)
  File "venv/lib/python3.8/site-packages/tensorpack/models/__init__.py", line 30, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "venv/lib/python3.8/site-packages/tensorpack/models/batch_norm.py", line 15, in <module>
    from .common import layer_register, VariableHolder
  File "venv/lib/python3.8/site-packages/tensorpack/models/common.py", line 6, in <module>
    from .tflayer import rename_tflayer_get_variable
  File "venv/lib/python3.8/site-packages/tensorpack/models/tflayer.py", line 134, in <module>
    monkeypatch_tf_layers()
  File "venv/lib/python3.8/site-packages/tensorpack/models/tflayer.py", line 117, in monkeypatch_tf_layers
    if get_tf_version_tuple() < (1, 4):
  File "venv/lib/python3.8/site-packages/tensorpack/tfutils/common.py", line 148, in get_tf_version_tuple
    return tuple(map(int, tf.VERSION.split('.')[:2]))
AttributeError: module 'tensorflow' has no attribute 'VERSION'

**Comment by mrdixitjain** [comment]
what is the tensorflow version used?
i'm using tensorflow 2.4.0 and i'm getting various errors with it.
